-- Fuzzy finder keymaps migrated from telescope -> snacks.picker
local Snacks = require("snacks")

local function map(mode, lhs, fn, desc)
	vim.keymap.set(mode, lhs, fn, { silent = true, noremap = true, desc = desc })
end

-- Files / MRU
map("n", "<Leader><Leader>", function()
	Snacks.picker.smart()
end, "Smart (MRU + files)")
map("n", "[_FuzzyFinder].", function()
	Snacks.picker.recent()
end, "Recent files")
map("n", "[_FuzzyFinder]<Leader>", function()
	Snacks.picker.files()
end, "Find files")
map("n", "<Leader>;", function()
	Snacks.picker.git_files()
end, "Git files")
map("n", "[_FuzzyFinder];", function()
	Snacks.picker.git_files()
end, "Git files")

-- Grep
map("n", "<Leader>,", function()
	Snacks.picker.grep()
end, "Grep")
map("n", "[_FuzzyFinder],", function()
	Snacks.picker.grep()
end, "Grep")
map("x", "[_FuzzyFinder],", function()
	Snacks.picker.grep_word()
end, "Grep selection")
map("n", "<Leader>/", function()
	Snacks.picker.grep_word()
end, "Grep word under cursor")
map("n", "[_FuzzyFinder]/", function()
	Snacks.picker.grep_word()
end, "Grep word under cursor")
map("n", "[_FuzzyFinder]*", function()
	Snacks.picker.grep_word()
end, "Grep word under cursor")
map("n", "[_FuzzyFinder]s", function()
	Snacks.picker.grep()
end, "Grep (live)")
map("n", "[_FuzzyFinder]>", function()
	Snacks.picker.grep()
end, "Grep in dir")

-- Buffers / misc
map("n", "[_FuzzyFinder]b", function()
	Snacks.picker.buffers()
end, "Buffers")
map("n", "[_FuzzyFinder]h", function()
	Snacks.picker.help()
end, "Help")
map("n", "[_FuzzyFinder]c", function()
	Snacks.picker.commands()
end, "Commands")
map("n", "[_FuzzyFinder]:", function()
	Snacks.picker.command_history()
end, "Command history")
map("c", "<C-t>", function()
	Snacks.picker.command_history()
end, "Command history")
map("n", "[_FuzzyFinder]t", function()
	Snacks.picker.treesitter()
end, "Treesitter symbols")
map("n", "[_FuzzyFinder]q", function()
	Snacks.picker.qflist()
end, "Quickfix")
map("n", "[_FuzzyFinder]l", function()
	Snacks.picker.loclist()
end, "Location list")
map("n", "[_FuzzyFinder]m", function()
	Snacks.picker.marks()
end, "Marks")
map("n", "[_FuzzyFinder]r", function()
	Snacks.picker.registers()
end, "Registers")
map("n", "[_FuzzyFinder]u", function()
	Snacks.picker.undo()
end, "Undo history")
map("n", "[_FuzzyFinder]cd", function()
	Snacks.picker.diagnostics()
end, "Diagnostics")
map("n", "[_FuzzyFinder]f", function()
	Snacks.explorer()
end, "File explorer")

-- Git
map("n", "[_FuzzyFinder]gs", function()
	Snacks.picker.git_status()
end, "Git status")
map("n", "[_FuzzyFinder]gc", function()
	Snacks.picker.git_log()
end, "Git commits")
map("n", "[_FuzzyFinder]gC", function()
	Snacks.picker.git_log_file()
end, "Git commits (buffer)")
map("n", "[_FuzzyFinder]gb", function()
	Snacks.picker.git_branches()
end, "Git branches")
