local stf = require("syntax-tree-surfer")
stf.setup()
vim.keymap.set("n", "J", function()
	stf.filtered_jump("default", true)
end, { noremap = true, silent = true })
vim.keymap.set("n", "K", function()
	stf.filtered_jump("default", false)
end, { noremap = true, silent = true })

vim.keymap.set("x", "J", "<cmd>STSSelectNextSiblingNode<cr>", { noremap = true, silent = true })
vim.keymap.set("x", "K", "<cmd>STSSelectPrevSiblingNode<cr>", { noremap = true, silent = true })
-- vim.keymap.set("x", "H", "<cmd>STSSelectParentNode<cr>", { noremap = true, silent = true })
-- vim.keymap.set("x", "L", "<cmd>STSSelectChildNode<cr>", { noremap = true, silent = true })
