#!/bin/bash

if [[ $1 == "--primary" ]]; then
  TYPE=$1
elif [[ $1 == "--clipboard" ]]; then
  TYPE=$1
else
  echo "arg error"
  exit 1
fi

STATE_FILE="/tmp/.i3blocks-clipboard-$TYPE.tmp"

if [[ ! -f "$STATE_FILE" ]]; then
  echo "unhidden" > $STATE_FILE
fi

function toggle_mode() {
  if cat "$STATE_FILE" | grep -q "unhidden"; then
    echo "hidden" > $STATE_FILE
  else
    echo "unhidden" > $STATE_FILE
  fi
}

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  toggle_mode
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  echo "---" | xsel $TYPE > /dev/null
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  toggle_mode
fi

#COMMAND=$(echo "($(xsel -o $TYPE | grep -o '^.\{0,5\}' | sed -e 's/[^a-zA-Z0-9\-]/_/g'))")
COMMAND=$(echo "($(xsel -o $TYPE | head -n 1 | grep -o '^.\{0,5\}'))")

if cat "$STATE_FILE" | grep -q "unhidden"; then
  echo $COMMAND
else
  echo "hidden"
fi

