#!/bin/bash

# ディレクトリの存在確認
if [ ! -d $HOME/.vim ];then
    echo "$HOME/.vim not found. Auto Make it"
    mkdir $HOME/.vim
fi

if [ ! -d $HOME/.vim/vimundo  ];then
    echo "$HOME/.vim/vimundo not found. Auto Make it"
    mkdir $HOME/.vim/vimundo
fi

if [ ! -d $HOME/.zsh ];then
    echo "$HOME/.zsh not found. Auto Make it"
    mkdir $HOME/.zsh
fi

if [ ! -d $HOME/.trash ];then
    echo "Make trash directory"
    mkdir $HOME/.trash
fi

# ファイルの存在確認
neobundle_readme='$HOME/.vim/bundle/neobundle.vim'
if [ ! -f "$neobundle_readme/README.md" ];then
    echo "Installing NeoBundle.."
    echo ""
    mkdir -p $HOME/.vim/bundle
    git clone https://github.com/Shougo/neobundle.vim.git $neobundle_readme
else
    git pull
fi

# ファイルの存在確認
auto_fu_zsh='$HOME/.zsh/auto-fu.zsh'
if [ ! -f $auto_fu_zsh ];then
    echo "Installing auto-fu.zsh..."
    echo ""
    git clone https://github.com/hchbaw/auto-fu.zsh.git $HOME/.zsh
else
    git pull
fi

# コマンドの存在確認
chkcmd(){
    existcmd=`which $1`
    if [ "$?" -ne 0 ];then
        echo "${1}コマンドが見つかりません"
    fi
}

#  
if [[ `apt-get --help >/dev/null 2>/dev/null` -eq 0 ]];then
    cmd="sudo apt-get install"
elif [[ `yum --help >/dev/null 2>/dev/null` -eq 0 ]];then
    cmd="sudo yum install"
else
    cmd="#";
fi

package="zsh vim git curl ctags" 
$cmd $package

chkcmd zsh
chkcmd git 


