-- ==============================================================
--           Disable                                          {{{
-- ==============================================================
-- cSpell:disable

-- -> mise ([tools] in .config/mise/config.toml and conf.d/neovim.toml),
--    servers enabled via vim.lsp.enable() in pluginconfig/nvim-lspconfig.lua
-- {
-- 	"mason-org/mason.nvim",
-- 	event = { "VeryLazy" },
-- 	build = ":MasonUpdate",
-- 	config = function()
-- 		require("rc/pluginconfig/mason")
-- 	end,
-- },
-- {
-- 	"mason-org/mason-lspconfig.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/mason-lspconfig")
-- 	end,
-- },

-- -> nvim-mini/mini.icons (with mock_nvim_web_devicons for compatibility)
-- {
-- 	"nvim-tree/nvim-web-devicons",
-- 	enabled = function()
-- 		return not os.getenv("DISABLE_DEVICONS") or os.getenv("DISABLE_DEVICONS") == "false"
-- 	end,
-- },
-- -> removed with telescope (snippets available via blink completion)
-- {
-- 	"benfowler/telescope-luasnip.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("telescope").load_extension("luasnip")
-- 	end,
-- },
-- AI
-- {
-- 	"bennypowers/nvim-regexplainer",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-regexplainer")
-- 	end,
-- },
--[[
{
	"nvim-telescope/telescope.nvim",
	enabled = false,
	event = { "VimEnter" },
	config = function()
		require("rc/pluginconfig/telescope")
	end,
	dependencies = {
		-- I don't know how to use it.
		-- {
		-- 	"prochri/telescope-all-recent.nvim",
		-- 	config = true,
		-- },
		{
			"nvim-telescope/telescope-github.nvim",
			config = function()
				require("telescope").load_extension("gh")
			end,
		},
		-- -> folke/snacks.nvim picker (ui_select)
		-- {
		-- 	"nvim-telescope/telescope-ui-select.nvim",
		-- 	config = function()
		-- 		require("telescope").load_extension("ui-select")
		-- 	end,
		-- },
		{
			"nvim-telescope/telescope-live-grep-args.nvim",
			config = function()
				require("telescope").load_extension("live_grep_args")
			end,
		},
		{
			"nvim-telescope/telescope-smart-history.nvim",
			config = function()
				require("telescope").load_extension("smart_history")
			end,
			build = function()
				os.execute("mkdir -p " .. vim.fn.stdpath("state") .. "databases/")
			end,
		},
		{ "nvim-telescope/telescope-symbols.nvim" },
		{
			"debugloop/telescope-undo.nvim",
			config = function()
				require("telescope").load_extension("undo")
			end,
		},
	},
},
]]
-- -> folke/snacks.nvim picker (smart / recent)
-- {
-- 	"nvim-telescope/telescope-frecency.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("telescope").load_extension("frecency")
-- 	end,
-- },
-- not used
-- {
-- 	"nvim-telescope/telescope-media-files.nvim",
-- 	event = "VeryLazy",
-- 	enabled = function()
-- 		return vim.fn.executable("ueberzug")
-- 	end,
-- 	config = function()
-- 		require("telescope").load_extension("media_files")
-- 	end,
-- },
-- -> folke/snacks.nvim picker (treesitter / lsp_symbols)
-- {
-- 	"crispgm/telescope-heading.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("telescope").load_extension("heading")
-- 	end,
-- },
-- {
-- 	"nvim-telescope/telescope-fzf-writer.nvim",
-- 	after = { "telescope.nvim" },
-- 	config = function()
-- 		require("telescope").load_extension("fzf_writer")
-- 	end,
-- },
-- I don't want to set items myself
-- use { "LinArcX/telescope-command-palette.nvim", 	after = { "telescope.nvim" } }
-- -> filer
-- {
-- 	"nvim-telescope/telescope-file-browser.nvim",
-- 	after = { "telescope.nvim" },
-- 	config = function()
-- 		require("telescope").load_extension("file_browser")
-- 	end,
-- },
-- use {"sunjon/telescope-arecibo.nvim",
--   after = {'telescope.nvim'},
--   rocks = {"openssl", "lua-http-parser"},
--   config = function() require('telescope').load_extension('arecibo') end
-- }
-- {
-- 	"LinArcX/telescope-command-palette.nvim",
-- 	after = { "telescope.nvim" },
-- 	config = function()
-- 		require("telescope").load_extension("command_palette")
-- 	end,
-- },
-- { "molleweide/LuaSnip-snippets.nvim", event = "VimEnter" },
-- -> removed with telescope (dap browse keymaps dropped)
-- {
-- 	"nvim-telescope/telescope-dap.nvim",
-- },
-- {
-- 	"andrewferrier/debugprint.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/debugprint")
-- 	end,
-- },
-- {
-- 	"cnshsliu/smp.nvim",
-- 	ft = { "markdown" },
-- },
-- use {'dbext.vim'} -- I get a helptag error. Disabled for now because I don't use it.
-- use {'tpope/vim-dadbod', event = "VimEnter"}
-- -> obsidian-nvim/obsidian.nvim (picker = snacks)
-- {
-- 	"nvim-telekasten/telekasten.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/telekasten")
-- 	end,
-- },
-- {
-- 	"antosha417/nvim-compare-with-clipboard",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-compare-with-clipboard")
-- 	end,
-- },
-- -> lualine + trouble
-- {
-- 	"nvim-treesitter/nvim-treesitter-context",
-- 	cmd = { "TSContextEnable" },
-- 	config = true,
-- },
-- {
-- 	"andersevenrud/nvim_context_vt",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim_context_vt")
-- 	end,
-- },
-- https://github.com/theHamsta/nvim-treesitter-pairs/pull/8
-- { "theHamsta/nvim-treesitter-pairs", event = "VimEnter" },
-- do not work correnctly
-- -> nvim-insx
-- {
-- 	"RRethy/nvim-treesitter-endwise",
-- 	event = "VimEnter",
-- 	dependencies = { { "nvim-treesitter/nvim-treesitter" } },
-- },
-- {
--   "hrsh7th/nvim-insx",
--   event = "VimEnter",
--   config = function()
--     require("rc/pluginconfig/nvim-insx")
--   end,
-- },
-- { "zsugabubus/crazy8.nvim", event = { "BufNewFile", "BufReadPost" } },
-- NMAC427/guess-indent.nvim
-- formatter
-- {
-- 	"rareitems/put_at_end.nvim",
-- 	event = { "VeryLazy" },
-- 	config = function()
-- 		require("rc/pluginconfig/put_at_end")
-- 	end,
-- },
-- use ime
-- {
-- 	"protex/better-digraphs.nvim",
-- 	event = "InsertEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/better-digraphs")
-- 	end,
-- },
-- use AI
-- {
-- 	"s1n7ax/nvim-comment-frame",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-comment-frame")
-- 	end,
-- },
-- {
-- 	"LudoPinelli/comment-box.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/comment-box")
-- 	end,
-- },
-- {'ygm2/rooter.nvim', event = "VimEnter"}
-- https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621
-- {
-- 	"jose-elias-alvarez/null-ls.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/null-ls")
-- 	end,
-- },
-- {
-- 	"nvimdev/guard.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/guard")
-- 	end,
-- },
-- {
-- 	"mhartington/formatter.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/formatter")
-- 	end,
-- },
-- {
-- 	"elentok/format-on-save.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/format-on-save")
-- 	end,
-- },
-- do not customize K mapping
-- { "tjdevries/nlua.nvim", event = "VimEnter" },
-- { "tjdevries/manillua.nvim", event = "VimEnter" },
-- I don't know how to use it
-- {
-- 	"Olical/conjure",
-- 	init = function()
-- 		vim.g["conjure#extract#tree_sitter#enabled"] = true
-- 	end,
-- 	cmd = { "ConjureConnect" },
-- },
-- {
--   "hrsh7th/cmp-cmdline",
--   event = "VimEnter"
-- },
-- {
--   "dmitmel/cmp-cmdline-history",
--   event = "VimEnter"
-- },
-- {
-- 	"sudormrfbin/cheatsheet.nvim",
-- 	dependencies = { { "nvim-telescope/telescope.nvim", opt = true } },
-- 	after = { "telescope.nvim" },
-- },
-- unused
-- {
-- 	"anuvyklack/pretty-fold.nvim",
-- 	dependencies = 'anuvyklack/nvim-keymap-amend',
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("pretty-fold").setup()
-- 		require("pretty-fold.preview").setup()
-- 	end,
-- },
-- can't jump to the file number
-- {
--   'ThePrimeagen/harpoon',
--   event = "VimEnter",
--   config = function() require 'rc/pluginconfig/harpoon' end
-- }
-- {
--   'brandoncc/telescope-harpoon.nvim',
--   event = "VimEnter",
--   config = function() require('telescope').load_extension('harpoon') end
-- }
-- @Vim script
-- { "wsdjeg/vim-fetch", event = "VimEnter" },
-- -> nvim-hlslens
-- {
-- 	"rapan931/utahraptor.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/utahraptor")
-- 	end,
-- },
-- {
-- 	"kevinhwang91/nvim-hlslens",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-hlslens")
-- 	end,
-- },
-- -> nvim-mini/mini.splitjoin
-- {
-- 	"Wansmer/treesj",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/treesj")
-- 	end,
-- },
-- https://github.com/neovim/neovim/pull/25872/
-- {
-- 	"yutkat/osc52.nvim",
-- 	event = "VeryLazy"
-- },
-- include yoink g:yoinkSyncSystemClipboardOnFocus
-- {
-- 	"AckslD/nvim-trevJ.lua",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-trevJ")
-- 	end,
-- },
-- {
-- 	"gbprod/substitute.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/substitute")
-- 	end,
-- },
-- {
-- 	"kylechui/nvim-surround",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-surround")
-- 	end,
-- },
-- {
-- 	"XXiaoA/ns-textobject.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/ns-textobject")
-- 	end,
-- },
-- I realized I don't like smart scrolling.
-- {
-- 	"declancm/cinnamon.nvim",
-- 	event = "CursorMoved",
-- 	config = function()
-- 		require("rc/pluginconfig/cinnamon")
-- 	end,
-- },
-- -> treesitter incremental selection
-- {
-- 	"ziontee113/syntax-tree-surfer",
-- 	after = "nvim-treesitter",
-- 	config = function()
-- 		require("rc/pluginconfig/syntax-tree-surfer")
-- 	end,
-- },
-- {
-- 	"wilfreddenton/history.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/history")
-- 	end,
-- },
-- not useful but cool
-- use {'nacro90/numb.nvim',
--  config = function() require'rc/pluginconfig/numb' end
-- }
-- -> nvim-mini/mini.operators (exchange) + nvim-mini/mini.ai (argument textobj)
-- {
-- 	"mizlan/iswap.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/iswap")
-- 	end,
-- },
-- -> lewis6991/satellite.nvim
-- {
-- 	"petertriho/nvim-scrollbar",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-scrollbar")
-- 	end,
-- 	dependencies = { { "kevinhwang91/nvim-hlslens" } },
-- },
-- original autocmd
-- {
-- 	"myusuf3/numbers.vim",
-- 	cmd = { "NumbersToggle", "NumbersOnOff" },
-- 	config = function()
-- 		vim.cmd("source ~/.config/nvim/rc/pluginconfig/numbers.vim")
-- 	end,
-- },
-- -> folke/snacks.nvim words (LSP documentHighlight based)
-- {
-- 	"tzachar/local-highlight.nvim",
-- 	config = function()
-- 		require("local-highlight").setup()
-- 	end,
-- },
-- {
-- 	"mvllow/modes.nvim",
-- 	after = { colorscheme },
-- 	config = function()
-- 		require("rc/pluginconfig/modes")
-- 	end,
-- },
-- {
-- 	"Pocco81/HighStr.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/HighStr")
-- 	end,
-- },
-- {
-- 	"Djancyp/better-comments.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/better-comments")
-- 	end,
-- },
-- {
-- 	"m00qek/baleia.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/baleia")
-- 	end,
-- },
-- {
-- 	"RRethy/vim-illuminate",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/vim-illuminate")
-- 	end,
-- },
-- {
-- 	"xiyaowong/nvim-cursorword",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-cursorword")
-- 	end,
-- },
-- mini.ai
-- {
-- 	"David-Kunz/treesitter-unit",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/treesitter-unit")
-- 	end,
-- },
-- {
--   "HiPhish/rainbow-delimiters.nvim",
--   event = "VeryLazy",
--   config = function()
--     -- patch https://github.com/nvim-treesitter/nvim-treesitter/issues/1124
--     if vim.fn.expand('%:p') ~= "" then
--       vim.cmd.edit({ bang = true })
--     end
--   end,
-- },
-- -> flash.nvim
-- {
-- 	"mfussenegger/nvim-treehopper",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-treehopper")
-- 	end,
-- },
-- conflict with flash
-- {
-- 	"edluffy/specs.nvim",
-- 	cmd = { "SpecsEnable" },
-- 	config = function()
-- 		require("rc/pluginconfig/specs")
-- 	end,
-- },
-- if vim.fn.executable('cargo') == 1 then
--   use {'wfxr/minimap.vim',
--     -- event = "VimEnter",
--     cmd = {'Minimap'},
--     build = 'cargo install --locked code-minimap'
--   }
-- end
-- archived
-- { "rinx/nvim-minimap", cmd = { "MinimapOpen" } },
-- startup-nvim/startup.nvim
-- use {'kizza/actionmenu.nvim', event = "VimEnter"}
-- {
-- 	"sunjon/stylish.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/stylish")
-- 	end,
-- },
-- {
-- 	"jcdickinson/codeium.nvim",
-- 	cmd = { "Codeium" },
-- 	config = true,
-- },
-- {
-- 	"CopilotC-Nvim/CopilotChat.nvim",
-- 	event = { "CmdlineEnter" },
-- 	opts = {
-- 		debug = false,
-- 	},
-- },
-- {
-- 	"EthanJWright/toolwindow.nvim",
-- 	dependencies = { { "akinsho/toggleterm.nvim", opt = true, event = "VimEnter" } },
-- 	after = { "trouble.nvim", "toggleterm.nvim" },
-- 	config = function()
-- 		require("rc/pluginconfig/toolwindow")
-- 	end,
-- },
-- weilbith/nvim-code-action-menu
-- RishabhRD/nvim-lsputils
-- aspeddro/lsp_menu.nvim
-- {
-- 	"nvimdev/lspsaga.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/lspsaga")
-- 	end,
-- },
-- {
-- 	"jinzhongjia/LspUI.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/LspUI")
-- 	end,
-- },
-- {
--   "hrsh7th/nvim-cmp",
--   event = "VimEnter",
--   config = function()
--     require("rc/pluginconfig/nvim-cmp")
--   end,
--   dependencies = {
--     { "hrsh7th/cmp-nvim-lsp" },
--     -- Duplicate popups. noice.nvim signature
--     -- { "hrsh7th/cmp-nvim-lsp-signature-help" },
--     { "hrsh7th/cmp-nvim-lsp-document-symbol" },
--     { "hrsh7th/cmp-buffer" },
--     { "hrsh7th/cmp-path" },
--     -- { "hrsh7th/cmp-omni" },
--     { "hrsh7th/cmp-nvim-lua" },
--     -- { "hrsh7th/cmp-copilot" },
--     { "hrsh7th/cmp-emoji" },
--     { "hrsh7th/cmp-calc" },
--     { "f3fora/cmp-spell" },
--     { "yutkat/cmp-mocword" },
--     { "saadparwaiz1/cmp_luasnip" },
--     {
--       "tzachar/cmp-tabnine",
--       build = "./install.sh",
--     },
--     { "ray-x/cmp-treesitter" },
--     { "lukas-reineke/cmp-rg" },
--     { "lukas-reineke/cmp-under-comparator" },
--     {
--       "onsails/lspkind-nvim",
--       config = function()
--         require("rc/pluginconfig/lspkind-nvim")
--       end,
--     },
--   },
-- },
--------------------------------
-- Vim script Library
-- @Vim script
-- {
-- 	"tpope/vim-repeat",
-- 	event = "VimEnter"
-- },
-- noice
-- {
-- 	"j-hui/fidget.nvim",
-- 	event = "BufEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/fidget")
-- 	end,
-- },
-- Archived
-- {
-- 	"tversteeg/registers.nvim",
-- 	event = "VeryLazy",
-- 	enable = function()
-- 		return vim.fn.has("clipboard") == 1
-- 	end,
-- 	config = function()
-- 		require("rc/pluginconfig/registers")
-- 	end,
-- },
-- {
-- 	"LinArcX/telescope-changes.nvim",
-- 	config = function()
-- 		require("telescope").load_extension("changes")
-- 	end,
-- },
-- {
-- 	"prescientmoon/scrap.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/scrap")
-- 	end,
-- },
-- {
-- 	"bfredl/nvim-luadev",
-- 	event = "VimEnter",
-- },
-- {
-- 	"klen/nvim-test",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-test")
-- 	end,
-- },
-- {
-- 	"AckslD/nvim-anywise-reg.lua",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-anywise-reg")
-- 	end,
-- },
-- -> grug-far.nvim
-- {
-- 	"nvim-pack/nvim-spectre",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-spectre")
-- 	end,
-- },
-- {
-- 	"gabrielpoca/replacer.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/replacer")
-- 	end,
-- },
-- { "nvim-treesitter/nvim-tree-docs" },
-- {
-- 	"jackMort/ChatGPT.nvim",
-- 	cmd = { "ChatGPT", "ChatGPTActAs" },
-- 	config = true,
-- },
-- { "weilbith/nvim-lsp-smag", after = "nvim-lspconfig" },
-- {
-- 	"kwkarlwang/bufresize.nvim",
-- 	event = "WinNew",
-- 	config = function()
-- 		require("rc/pluginconfig/bufresize")
-- 	end,
-- },
-- {
-- 	"jghauser/mkdir.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("mkdir")
-- 	end,
-- },
-- {
-- 	"kristijanhusak/line-notes.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/line-notes")
-- 	end,
-- },
-- { "nvim-lua/popup.nvim" },
-- { "nvim-treesitter/nvim-treesitter-textobjects", event = "VeryLazy" },
-- -> archived
-- {
-- 	"ecthelionvi/NeoComposer.nvim",
-- 	config = true,
-- },
-- -> archived
-- {
--   "ziontee113/syntax-tree-surfer",
--   event = "VeryLazy",
--   config = function()
--     require("rc/pluginconfig/syntax-tree-surfer")
--   end,
-- },
-- {
--   "zapling/mason-conform.nvim",
--   event = "VeryLazy",
--   config = function()
--     require("mason-conform").setup()
--   end,
-- },
-- {
--   "GustavoKatel/sidebar.nvim",
--   cmd = { "SidebarNvimToggle" },
--   config = function()
--     require("rc/pluginconfig/sidebar")
--   end,
-- },
-- -> "folke/snacks.nvim"
-- {
-- 	"akinsho/toggleterm.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/toggleterm")
-- 	end,
-- },
-- -> "folke/snacks.nvim"
-- {
-- 	"lukas-reineke/indent-blankline.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/indent-blankline")
-- 	end,
-- },
-- -> "folke/snacks.nvim"
-- {
-- 	"goolord/alpha-nvim",
-- 	event = "BufEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/alpha-nvim")
-- 	end,
-- },
-- -> "folke/snacks.nvim"
-- {
-- 	"nvim-neo-tree/neo-tree.nvim",
-- 	event = "VimEnter",
-- 	branch = "main",
-- 	config = function()
-- 		require("rc/pluginconfig/neo-tree")
-- 	end,
-- },
-- -> "folke/snacks.nvim"
-- {
-- 	"famiu/bufdelete.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/bufdelete")
-- 	end,
-- },
-- -> "folke/snacks.nvim"
-- {
-- 	"rcarriga/nvim-notify",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-notify")
-- 	end,
-- },
-- {
-- 	"stevearc/dressing.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/dressing")
-- 	end,
-- },
--	{
--		"folke/neodev.nvim",
--		config = function()
--			require("rc/pluginconfig/neodev")
--		end,
--	},
--	{
--		"hek14/symbol-overlay.nvim",
--		event = "VeryLazy",
--		config = function()
--			require("rc/pluginconfig/symbol-overlay")
--		end,
--	},
-- -> nvim-highlight-colors
--	{
--		"norcalli/nvim-colorizer.lua",
--		event = "VeryLazy",
--		config = true,
--	},
-- -> copilot.lua
-- {
-- 	"zbirenbaum/copilot-cmp",
-- 	config = true,
-- },
-- Sometimes it gets stuck at startup.
-- {
-- 	"ahmedkhalf/project.nvim",
-- 	event = "BufWinEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/project")
-- 	end,
-- },
-- {
-- 	"Pocco81/AbbrevMan.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/AbbrevMan")
-- 	end,
-- },
-- ->HiPhish/rainbow-delimiters.nvim
-- {
-- 	"HiPhish/nvim-ts-rainbow2",
-- 	event = "BufReadPost",
-- 	config = function()
-- 		-- patch https://github.com/nvim-treesitter/nvim-treesitter/issues/1124
-- 		vim.cmd.edit({ bang = true })
-- 	end,
-- },
-- -> flash.nvim
-- {
-- 	"ggandor/leap.nvim",
-- 	event = "VeryLazy",
-- 	dependencies = {
-- 		"yutkat/leap-word.nvim",
-- 		config = function()
-- 			require("rc/pluginconfig/leap-word")
-- 		end,
-- 	},
-- 	config = function()
-- 		require("rc/pluginconfig/leap")
-- 	end,
-- },
-- {
-- 	"ggandor/leap-ast.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/leap-ast")
-- 	end,
-- },
-- {
-- 	"ggandor/flit.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("rc/pluginconfig/flit")
-- 	end,
-- },
-- do not use
-- { "vigoux/architext.nvim" },
-- {
-- 	"phaazon/hop.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/hop")
-- 	end,
-- },
-- -> leap.nvim
-- {
-- 	"ggandor/lightspeed.nvim",
-- 	event = "VimEnter",
-- 	init = function()
-- 		vim.g.lightspeed_no_default_keymaps = true
-- 	end,
-- 	config = function()
-- 		require("rc/pluginconfig/lightspeed")
-- 	end,
-- },
-- -> "cnshsliu/smp.nvim",
-- { "iamcco/markdown-preview.nvim", ft = { "markdown" }, build = ":call mkdp#util#install()" },
-- -- @Vim script
-- {
-- 	"AndrewRadev/linediff.vim",
-- 	cmd = { "Linediff" },
-- },
-- { "neoclide/jsonc.vim", ft = { "json", "jsonc" } },
-- { "MTDL9/vim-log-highlighting", ft = { "log" } },
-- { "mechatroner/rainbow_csv", ft = { "csv" } },
-- buggy
-- use markdown-preview.nvim
-- if vim.fn.executable('glow') == 1 then
--   use {'npxbr/glow.nvim',
--     ft = {'markdown'},
--     build = ':GlowInstall',
--   }
-- end
-- archived
-- { "Pocco81/DAPInstall.nvim", after = { "nvim-dap" } },
-- { "rhysd/committia.vim" },
-- don't work
-- use {'tanvirtin/vgit.nvim'}
-- lua buf too simple
-- use {'windwp/nvim-projectconfig'}
-- use {
--   'ldelossa/litee-calltree.nvim',
--   after = {'nvim-lspconfig', 'litee.nvim'},
--   config = function() require('litee.calltree').setup({}) end
-- }
-- use {'ElPiloto/sidekick.nvim'}
-- {
-- 	"stevearc/aerial.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/aerial")
-- 	end,
-- },
-- use {
--   'simrat39/symbols-outline.nvim',
--   event = "VimEnter",
--   config = function() require 'rc/pluginconfig/symbols-outline' end
-- }
-- use {
--   'ldelossa/litee-symboltree.nvim',
--   after = {'nvim-lspconfig', 'litee.nvim'},
--   config = function() require('litee.symboltree').setup({}) end
-- }
-- { "gpanders/editorconfig.nvim", event = "VimEnter" },
-- -> null-ls
-- use {
--   'lukas-reineke/format.nvim',
--   event = "VimEnter",
--   config = function() require 'rc/pluginconfig/format' end
-- }
-- -> null-ls
-- {
-- 	"cappyzawa/trim.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("trim").setup()
-- 	end,
-- },
-- {
-- 	"yutkat/taskrun.nvim",
-- 	after = { "toggleterm.nvim", "nvim-notify" },
-- 	config = function()
-- 		require("rc/pluginconfig/taskrun")
-- 	end,
-- },
-- {
-- 	"pianocomposer321/yabs.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/yabs")
-- 	end,
-- },
-- micmine/jumpwire.nvim
-- { "tpope/vim-apathy", event = "VimEnter" },
-- {
-- 	"kana/vim-altr",
-- 	event = "VimEnter",
-- 	config = function()
-- 		vim.cmd("source ~/.config/nvim/rc/pluginconfig/vim-altr.vim")
-- 	end,
-- },
-- {
-- 	"m4xshen/autoclose.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/autoclose")
-- 	end,
-- },
-- {
-- 	"windwp/nvim-autopairs",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-autopairs")
-- 	end,
-- },
-- ZhiyuanLck/smart-pairs
-- use {'steelsojka/pears.nvim',
--   after = {'nvim-treesitter'},
--   config = function() require'rc/pluginconfig/pears' end
-- }
-- -> nvim-insx
-- {
-- 	"windwp/nvim-ts-autotag",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-ts-autotag")
-- 	end,
-- 	dependencies = { { "nvim-treesitter/nvim-treesitter" } },
-- },
-- {
--   'abecodes/tabout.nvim',
--   after = {'nvim-treesitter', 'coc.nvim'},
--   config = function() require 'rc/pluginconfig/tabout' end
-- }
--
-- don't work on rust
-- {
-- 	"TornaxO7/tree-setter",
-- 	after = { "nvim-treesitter" },
-- },
-- use {
--   'yutkat/dps-coding-now.nvim',
--   cond = function() return os.getenv("CODING_NOW_GITHUB_TOKEN") ~= nil end,
--   after = {'denops.vim'}
-- }
-- startup time didn't change much
-- {
-- 	"lewis6991/impatient.nvim",
-- 	config = function()
-- 		require("impatient")
-- 	end,
-- },
-- Furkanzmc/zettelkasten.nvim
-- if vim.fn.executable("zk") == 1 then
-- 	{
-- 		"mickael-menu/zk-nvim",
-- 		event = "VimEnter",
-- 		build = function()
-- 			local dir = vim.fn.stdpath("data") .. "/zk/"
-- 			os.execute("mkdir -p " .. dir)
-- 		end,
-- 		config = function()
-- 			require("rc/pluginconfig/zk-nvim")
-- 		end,
-- 	},
-- end
-- use {'stevearc/gkeep.nvim', event = "VimEnter", build = ':UpdateRemotePlugins'}
-- not use
-- {
-- 	"mrjones2014/legendary.nvim",
-- 	after = { "dressing.nvim", "telescope.nvim" },
-- 	config = function()
-- 		require("rc/pluginconfig/legendary")
-- 	end,
-- },
-- use {'kassio/neoterm'} -- include repl
-- use {'numToStr/FTerm.nvim'}
-- -> cmp-cmdline
-- wilder did not work
-- use {'VonHeikemen/fine-cmdline.nvim', dependencies = "MunifTanjim/nui.nvim"}
-- -> filer
-- https://github.com/neovim/neovim/pull/19419
-- {
-- 	"lewis6991/spellsitter.nvim",
-- 	after = "nvim-treesitter",
-- 	config = function()
-- 		require("rc/pluginconfig/spellsitter")
-- 	end,
-- },
-- {
-- 	"Shatur/neovim-session-manager",
-- 	config = function()
-- 		require("rc/pluginconfig/neovim-session-manager")
-- 	end,
-- },
-- {
-- 	"olimorris/persisted.nvim",
-- 	config = function()
-- 		require("rc/pluginconfig/persisted")
-- 	end,
-- },
-- don't work
-- use {'edluffy/hologram.nvim', config = function() require 'rc/pluginconfig/hologram' end}
-- set diffopt+=internal,algorithm:patience
-- { "chrisbra/vim-diff-enhanced", event = "VimEnter" },
-- {
-- 	"kevinhwang91/nvim-fundo",
-- 	dependencies = { "kevinhwang91/promise-async", module = { "promise", "async" } },
-- 	event = "VimEnter",
-- 	build = function()
-- 		require("fundo").install()
-- 	end,
-- 	config = function()
-- 		require("fundo").setup()
-- 	end,
-- },
-- -> do not use eventignore! https://github.com/luukvbaal/stabilize.nvim/commit/718561393f885dbbc9de8ed71089772af0dbbb3f
-- use {
--   'luukvbaal/stabilize.nvim',
--   event = "VimEnter",
--   config = function() require 'rc/pluginconfig/stabilize' end
-- }
-- {
-- 	"tkmpypy/chowcho.nvim",
-- 	event = "WinNew",
-- 	config = function()
-- 		require("rc/pluginconfig/chowcho")
-- 	end,
-- },
-- I didn't use zen-mode much
-- use {'kdav5758/TrueZen.nvim', cmd = {'TZAtaraxis', 'TZMinimalist', 'TZBottom', 'TZTop', 'TZLeft'}}
-- use {'folke/zen-mode.nvim', cmd = {'ZenMode'}}
-- There are Lua plugin. I haven't tried it yet because I'm satisfied with coc.
-- norcalli/nvim-colorizer.lua
-- use {'powerman/vim-plugin-AnsiEsc', event = "VimEnter"}
-- -> use hop
-- mfussenegger/nvim-treehopper
-- {
-- 	"bryall/contextprint.nvim",
-- 	after = { "nvim-treesitter" },
-- 	config = function()
-- 		require("rc/pluginconfig/contextprint")
-- 	end,
-- },
-- Error on :Gina status
-- use {
--   'code-biscuits/nvim-biscuits',
--   after = {'nvim-treesitter', colorscheme},
--   config = function() require 'rc/pluginconfig/nvim-biscuits' end
-- }
-- {
-- 	"nvim-treesitter/playground",
-- 	lazy = false
-- },
-- {
-- 	"nvim-telescope/telescope-project.nvim",
-- 	after = { "telescope.nvim" },
-- 	config = function()
-- 		require("telescope").load_extension("project")
-- 	end,
-- },
-- {
-- 	"nvim-telescope/telescope-vimspector.nvim",
-- 	after = { "telescope.nvim" },
-- 	config = function()
-- 		require("telescope").load_extension("vimspector")
-- 	end,
-- },
-- {
-- 	"nvim-telescope/telescope-ghq.nvim",
-- 	after = { "telescope.nvim" },
-- 	config = function()
-- 		require("telescope").load_extension("ghq")
-- 	end,
-- },
-- {
-- 	"nvim-telescope/telescope-packer.nvim",
-- 	config = function()
-- 		require("telescope").load_extension("packer")
-- 	end,
-- },
-- use {
--   'ray-x/navigator.lua',
--   after = 'mason.nvim',
--   dependencies = {'ray-x/guihua.lua', build = 'cd lua/fzy && make', opt = true},
--   config = function() require 'rc/pluginconfig/navigator' end
-- }
-- use {
--   'onsails/diaglist.nvim',
--   after = 'nvim-lspconfig',
--   config = function() require 'rc/pluginconfig/diaglist' end
-- }
-- -> lspsaa
-- use {
--   'rmagatti/goto-preview',
--   after = 'nvim-lspconfig',
--   config = function() require 'rc/pluginconfig/goto-preview' end
-- }
-- -> lspsaa
-- use {
--   'filipdutescu/renamer.nvim',
--   after = 'nvim-lspconfig',
--   config = function() require 'rc/pluginconfig/renamer' end
-- }
-- -> lspsaa
-- use {
--   'kosayoda/nvim-lightbulb',
--   after = 'nvim-lspconfig',
--   config = function() require 'rc/pluginconfig/nvim-lightbulb' end
-- }
-- use {'nvim-lua/lsp-status.nvim', after = 'nvim-lspconfig'}
-- use {
--   'nvim-lua/lsp_extensions.nvim',
--   after = 'mason.nvim',
--   config = function() require 'rc/pluginconfig/lsp_extensions' end
-- }
-- -> hrsh7th/cmp-nvim-lsp-signature-help, hrsh7th/cmp-nvim-lsp-document-symbol
-- {
-- 	"ray-x/lsp_signature.nvim",
-- 	after = "nvim-lspconfig",
-- 	config = function()
-- 		require("rc/pluginconfig/lsp_signature")
-- 	end,
-- },
-- {
-- 	"tamago324/nlsp-settings.nvim",
-- 	after = { "nvim-lspconfig" },
-- 	config = function()
-- 		require("rc/pluginconfig/nlsp-settings")
-- 	end,
-- },
-- library for litee
-- use {
--   'ldelossa/litee.nvim',
--   after = 'nvim-lspconfig',
--   config = function() require('litee.lib').setup({}) end
-- }

-- -> lspsaga
-- {
-- 	"SmiteshP/nvim-navic",
-- 	init = function()
-- 		require("rc/pluginconfig/nvim-navic")
-- 	end,
-- },
-- Archived
-- {
-- 	"folke/lsp-colors.nvim",
-- },
-- use({
-- 	"gbprod/yanky.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/yanky")
-- 	end,
-- })
-- use({
-- 	"bfredl/nvim-miniyank",
-- 	event = "VimEnter",
-- 	config = function()
-- 		vim.cmd("source ~/.config/nvim/rc/pluginconfig/nvim-miniyank.vim")
-- 	end,
-- })
-- -> AckslD/nvim-neoclip.lua
-- use({
-- 	"gennaro-tedesco/nvim-peekup",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-peekup")
-- 	end,
-- })
-- use({
-- 	"johmsalas/text-case.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/text-case")
-- 	end,
-- })
-- -> ModeChanged
-- use({
-- 	"kevinhwang91/nvim-hclipboard",
-- 	after = { "LuaSnip" },
-- 	config = function()
-- 		require("hclipboard").start()
-- 	end,
-- })
-- -> andrewferrier/debugprint.nvim
-- use({
-- 	"sentriz/vim-print-debug",
-- 	event = "VimEnter",
-- 	config = function()
-- 		vim.cmd("source ~/.config/nvim/rc/pluginconfig/vim-print-debug.vim")
-- 	end,
-- })
-- -> williamboman/mason.nvim
-- use({
-- 	"williamboman/nvim-lsp-installer",
-- 	after = { "nvim-lspconfig", "cmp-nvim-lsp", "nlsp-settings.nvim" },
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-lsp-installer")
-- 	end,
-- })
-- use({
-- 	"Vonr/align.nvim",
-- 	module = "align",
-- })
-- -> jinh0/eyeliner.nvim
-- use({
-- 	"unblevable/quick-scope",
-- 	event = "VimEnter",
-- 	config = function()
-- 		vim.cmd("source ~/.config/nvim/rc/pluginconfig/quick-scope.vim")
-- 	end,
-- })
-- because generate the file contents automatically
-- use {'vigoux/templar.nvim',
--   event = "VimEnter"
-- }
-- -> uga-rosa/translate.nvim
-- coc-translator
-- use({
-- 	"voldikss/vim-translator",
-- 	event = "VimEnter",
-- 	config = function()
-- 		vim.cmd("source ~/.config/nvim/rc/pluginconfig/vim-translator.vim")
-- 	end,
-- })
-- -> nvim-trevJ.lua
-- use({
-- 	"AckslD/nvim-revJ.lua",
-- 	requires = {
-- 		{ "kana/vim-textobj-user", event = "VimEnter" },
-- 		{ "sgur/vim-textobj-parameter", after = { "vim-textobj-user" } },
-- 	},
-- 	after = { "vim-textobj-user", "vim-textobj-parameter" },
-- 	config = function()
-- 		require("rc/pluginconfig/nvim-revJ")
-- 	end,
-- })
-- archived
-- use({
-- 	"akinsho/dependency-assist.nvim",
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("rc/pluginconfig/dependency-assist")
-- 	end,
-- })
-- -> nvim-bqf
-- use {'yssl/QFEnter',
--   event = "VimEnter"
-- }
-- conflict with vim-test's quickfix
-- use {'itchyny/vim-qfedit' --should compare with use 'stefandtw/quickfix-reflector.vim'}
-- -> zettelkasten
-- use({
-- 	"mtth/scratch.vim",
-- 	cmd = { "Scratch" },
-- 	config = function()
-- 		vim.cmd("source ~/.config/nvim/rc/pluginconfig/scratch.vim")
-- 	end,
-- })
-- -> bfredl/nvim-miniyank
-- use {
--   'svermeulen/vim-yoink',
--   event = "VimEnter",
--   config = function() vim.cmd('source ~/.config/nvim/rc/pluginconfig/vim-yoink.vim') end
-- }
-- -> tkmpypy/chowcho.nvim
-- use {'dstein64/vim-win',
--   config = function() vim.cmd('source ~/.config/nvim/rc/pluginconfig/vim-win.vim') end
-- }
