force_keyboard_focus = false    # forces keyboard forcus to stay in Walker
close_when_open = true          # close walker when invoking while already opened
selection_wrap = false          # wrap list if at bottom or top
global_argument_delimiter = "#" # query: firefox#https://benz.dev => part after delimiter will be ignored when querying. this should be the same as in the elephant config
keep_open_modifier = "shift"    # won't close on activation, but rather select the next item in the list
exact_search_prefix = "'"       # disable fuzzy searching
theme = "default"               # theme to use
disable_mouse = false           # disable mouse (on input and list only)

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "Search", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
close = "Escape"
next = "Down"
previous = "Up"
toggle_exact = "ctrl e"
resume_last_query = "ctrl r"
quick_activate = ["F1", "F2", "F3", "F4"]

[providers]
default = [
  "desktopapplications",
  "calc",
] # providers to be queried by default
empty = ["desktopapplications"] # providers to be queried when query is empty

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = "sys "
provider = "menus:power"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[providers.providerlist]
default = "activate"
activate = "Return"

[providers.clipboard]
time_format = "%d.%m. - %H:%M" # format for the clipboard item date
default = "copy"
copy = "Return"
delete = "ctrl d"
edit = "ctrl o"
toggle_images_only = "ctrl i"

[providers.desktopapplications]
default = "start"
start = "Return"
start_keep_open = "shift Return"
remove_history = "ctrl BackSpace"
toggle_pin = "ctrl p"

[providers.menus]
default = "activate"
activate = "Return"
remove_history = "ctrl BackSpace"
