# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bfb924ce-e051-4a15-9ca3-263427c4eed0";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."luks-5da29728-0bcc-4e7c-b71b-ee6eb799f5eb".device = "/dev/disk/by-uuid/5da29728-0bcc-4e7c-b71b-ee6eb799f5eb";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FAD3-38F9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
