name: Install Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    timeout-minutes: 30
    steps:
      - name: Install required packages
        run: apt-get update && apt-get install -y git sudo curl xz-utils
      - name: Setup test user
        run: |
          useradd -m -s /bin/bash test
          echo 'test ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
      - name: Clone repository
        run: |
          git clone --no-single-branch https://github.com/${{ github.repository }} /home/test/dotfiles
          cd /home/test/dotfiles
          git fetch origin ${{ github.sha }}
          git checkout ${{ github.sha }}
      - name: Configure git safe directory and fix ownership
        run: |
          git config --global --add safe.directory "/home/test/dotfiles"
          chown -R test:test /home/test/dotfiles
      - name: Run install script (single-user mode)
        run: |
          cd /home/test/dotfiles
          sudo -u test bash -c './install.sh --single'
        timeout-minutes: 15
      - name: Apply Home Manager configuration
        run: |
          sudo -u test bash -c 'cd /home/test/dotfiles && export PATH="$HOME/.nix-profile/bin:$PATH" && home-manager switch --flake .#test'
        timeout-minutes: 10

  fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    timeout-minutes: 30
    steps:
      - name: Install required packages
        run: dnf clean all && dnf install -y git sudo curl
      - name: Setup test user
        run: |
          useradd -m -s /bin/bash test
          echo 'test ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
      - name: Clone repository
        run: |
          git clone --no-single-branch https://github.com/${{ github.repository }} /home/test/dotfiles
          cd /home/test/dotfiles
          git fetch origin ${{ github.sha }}
          git checkout ${{ github.sha }}
      - name: Configure git safe directory and fix ownership
        run: |
          git config --global --add safe.directory "/home/test/dotfiles"
          chown -R test:test /home/test/dotfiles
      - name: Run install script (single-user mode)
        run: |
          cd /home/test/dotfiles
          sudo -u test bash -c './install.sh --single'
        timeout-minutes: 15
      - name: Verify Nix installation
        run: |
          sudo -u test bash -c 'export PATH="$HOME/.nix-profile/bin:$PATH" && nix --version'
      - name: Apply Home Manager configuration
        run: |
          sudo -u test bash -c 'cd /home/test/dotfiles && export PATH="$HOME/.nix-profile/bin:$PATH" && home-manager switch --flake .#test'
        timeout-minutes: 10

  arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    timeout-minutes: 30
    steps:
      - name: Update packages and install requirements
        run: |
          pacman -Syyu --noconfirm
          pacman -S --noconfirm git sudo curl
      - name: Setup test user
        run: |
          useradd -m -s /bin/bash test
          echo 'test ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
      - name: Clone repository
        run: |
          git clone --no-single-branch https://github.com/${{ github.repository }} /home/test/dotfiles
          cd /home/test/dotfiles
          git fetch origin ${{ github.sha }}
          git checkout ${{ github.sha }}
      - name: Configure git safe directory and fix ownership
        run: |
          git config --global --add safe.directory "/home/test/dotfiles"
          chown -R test:test /home/test/dotfiles
      - name: Run install script (single-user mode)
        run: |
          cd /home/test/dotfiles
          sudo -u test bash -c './install.sh --single'
        timeout-minutes: 15
      - name: Verify Nix installation
        run: |
          sudo -u test bash -c 'export PATH="$HOME/.nix-profile/bin:$PATH" && nix --version'
      - name: Apply Home Manager configuration
        run: |
          sudo -u test bash -c 'cd /home/test/dotfiles && export PATH="$HOME/.nix-profile/bin:$PATH" && home-manager switch --flake .#test'
        timeout-minutes: 10
      - name: Test complete setup (following README steps)
        run: |
          sudo -u test bash -c '
            cd /home/test/dotfiles
            export PATH="$HOME/.nix-profile/bin:$PATH"
            # Test zsh plugin installation (exec zsh equivalent)
            export TERM=screen-256color
            export ZSHRC_CI_TEST=true
            zsh -c "echo \"Zsh plugins test completed\""
            # Test neovim plugin installation
            if command -v nvim >/dev/null 2>&1; then
              timeout 300 nvim --headless -c "Lazy! sync" -c "qall" || echo "Neovim plugin sync completed with timeout (expected in CI)"
            else
              echo "Neovim not found, checking if it should be available..."
            fi
          '
        env:
          TERM: screen-256color
          ZSHRC_CI_TEST: "true"

  nixos:
    runs-on: ubuntu-latest
    container: nixos/nix:latest
    timeout-minutes: 30
    steps:
      - name: Enable flake
        run: |
          echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
          nix profile remove man-db
      - name: Set HOME to /root
        run: echo "HOME=/root" >> $GITHUB_ENV
      - name: Clone repository
        run: |
          git clone --no-single-branch https://github.com/${{ github.repository }} /root/dotfiles
          cd /root/dotfiles
          git fetch origin ${{ github.sha }}
          git checkout ${{ github.sha }}
          git config --global --add safe.directory "/root/dotfiles"
      - name: Run install script (NixOS environment setup)
        run: |
          cd /root/dotfiles && ./install.sh
        timeout-minutes: 10
      - name: Apply Home Manager configuration
        run: |
          cd /root/dotfiles && export PATH="$HOME/.nix-profile/bin:$PATH" && home-manager switch --flake .#container
        timeout-minutes: 15

